# Generated by Django 4.1.6 on 2023-02-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='introduction',
            field=models.TextField(default='default'),
        ),
    ]
