# Generated by Django 4.1.6 on 2023-02-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
