# Generated by Django 4.1.6 on 2023-02-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Feed', '0002_comment_like_feed_content_alter_feed_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='nickname',
            field=models.CharField(default='default', max_length=255),
        ),
    ]
